### ISSUE TITLE
Simulate server initiated connection ends

### ISSUE THREAD

**Issue by amtrack** [andris9/hoodiecrow#17]
I would like to test my IMAP client to properly handle server initiated connection ends like
"remote has ended connection" or "session has expired".
Is there a way to do so?

`server.close(callback);` does seem to wait until the clients have disconnected, which is not what i want.

**Comment by andris9** [comment]
Currently this is not possible but I guess it would make sense to add it. I don't know when I have time for this though

**Comment by amtrack** [comment]
OK, i see. Thanks anyway!
