### ISSUE TITLE
toString("binary") is deprecated - how would I replace it?

### ISSUE THREAD

**Issue by TimeForAChange** [andris9/hoodiecrow#19]
**1)**

In `mimeparser.js` constructor function `Parser` there is a line

        this.rfc822 = (rfc822 || "").toString("binary");

The [node.js API page for Buffer](https://nodejs.org/api/buffer.html#buffer_buffer) says 

> 'binary' - A way of encoding raw binary data into strings by using only the first 8 bits of each character. This encoding method is deprecated and should be avoided in favor of Buffer objects where possible. This encoding will be removed in future versions of Node.js.

Unfortunately I have no idea how to replace it - after, all this entire parser _does_ require a string. Using 'utf8', for example, results in garbage of non-ascii characters in the body of emails - even if they are UTF8.

**2)**

ALSO: In the configuration objects I tried handing over a Buffer `{raw: myBuffer}` with the email BLOB. However, this resulted in garbage. Only when I changed it to `{raw: myBuffer.toString('binary')}` did it work. I don't understand, it should be the exact same if I don't add `toString` because it's in the `Parser` constructor. I'm confused

**Comment by TimeForAChange** [comment]
I think I know why **2)** fails: `raw` is left untouched, the `toString("binary")` only takes place within the parser, so the string that is sent to the client is treated as UTF8!

I think it's in file `handlers/fetch.js`, the function `fetchHandlers.BODY`. The "binary treatment" is fully encapsulated in `mimeparser.js`. The string under message property `raw` remains unaffected and in that function is implicitly converted with `toString()` I believe (definitely not treated as "binary" string).

So the `toString("binary")` in mimeparser.js is misplaced:

Either the string already is binary, i.e. somebody already ensured that the string under `raw` is of that type, **or** the same conversion will have to go to the fetch handler functions that return the string that is sent to the client.

**Comment by andris9** [comment]
1. "binary" has been "deprecated" more than five years by now basically since the beginning of Node.js and it hasn't been going anywhere, so I assume it continues to be safe to use.
  2. `raw` handling depends on the context. If you fetch a subpart, then yes, it is converted to binary and parsed, if you fetch the entire message with BODY[] then it is not parsed and not converted.

**Comment by TimeForAChange** [comment]
> if you fetch the entire message with BODY[]

The command Thunderbird sends is 

    11 UID fetch 4 (UID RFC822.SIZE BODY[])

and I have to add `toString("binary")` when I set `raw`. Shouldn't it work when I leave the Buffer object on that object?

**Comment by andris9** [comment]
Anyway, I'm not really doing anything with Hoodiecrow anymore as I've moved on to an async IMAP server project where content is loaded from an async backend (not open source), so if you want to update behaviors like this and make sure that raw is always converted to "binary" (BODY[] value is generated [here](https://github.com/andris9/hoodiecrow/blob/272c50bf13dfa9a5a31f692294d3f9c98b4a7308/lib/commands/handlers/fetch.js#L27)) then make a pull request with the change and I pull it.

**Comment by TimeForAChange** [comment]
Wouldn't the correct thing to do be to leave the ticket open if you don't want to solve it? I have no issues with you not solving it, but why close a valid ticket then? I already opened another ticket pointing here in the seagull project that still seems to be maintained. I'm trying to get into the code myself but this takes time.

**Comment by andris9** [comment]
I don't consider it unresolved. "binary" is still usable and the docs never say that you can use Buffers as message values. Hoodiecrow is supposed to support JSON as the input and this it does.

**Comment by TimeForAChange** [comment]
Last Q (I think): What's the point of `toString("binary")' in `mimeparser.js` then? It can be removed, right?

**Comment by TimeForAChange** [comment]
Okay, not last question - can one buy that other project? Because we are exactly looking for a node.js IMAP server. Small - not a large-deployment server, but one "per user" for "private data". We provide data via an IMAP interface, it's not really a mail server, we just use that API because there are plenty of clients. So we are looking for a module to integrate to offer locally stored data via IMAP.

**Comment by andris9** [comment]
Not sure at this point as the imap server I've been working with is not built to be a general purpose product but it's for a specific service. Who's "we"?

**Comment by TimeForAChange** [comment]
"we": At this point a few people working on a prototype for a product idea. But it's a serious project, money has been invested and the people planning it are "old people" :-) At this point I'll hack hoodiecrow, good enough for the prototype (and the fact that it's so limited is actually <i>good</i>), but my guess is that should it go to production there will be issues with this or that IMAP client, and I don't think we want to become IMAP server specialists.

**Comment by andris9** [comment]
Ok. If I ever have anything to offer then I'll contact you
